// This file is automatically generated. Please do not change this file!
export const detail: string;
export const error: string;
export const message: string;
export const serverHealthMessagesContainer: string;
export const serverHealthStatus: string;
export const serverHealthStatuses: string;
export const timestamp: string;
export const warning: string;
