// This file is automatically generated. Please do not change this file!
export const detail: string;
export const error: string;
export const mappings: string;
export const message: string;
export const names: string;
export const serverHealthMessagesContainer: string;
export const serverHealthStatus: string;
export const serverHealthStatuses: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const timestamp: string;
export const version: string;
export const warning: string;
