[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="enableAdminAccessTokensSPA" type="boolean" --]
[#-- @ftlvariable name="controllerName" type="java.lang.String" --]
[#-- @ftlvariable name="currentUser" type="com.thoughtworks.go.server.domain.Username" --]
[#-- @ftlvariable name="currentVersion" type="com.thoughtworks.go.CurrentGoCDVersion" --]
[#-- @ftlvariable name="currentGoCDVersion" type="java.lang.String" --]
[#-- @ftlvariable name="railsAssetsService" type="com.thoughtworks.go.server.service.RailsAssetsService" --]
[#-- @ftlvariable name="securityService" type="com.thoughtworks.go.server.service.SecurityService" --]
[#-- @ftlvariable name="maintenanceModeService" type="com.thoughtworks.go.server.service.MaintenanceModeService" --]
[#-- @ftlvariable name="webpackAssetsService" type="com.thoughtworks.go.server.service.WebpackAssetsService" --]
[#-- @ftlvariable name="viewName" type="java.lang.String" --]
[#-- @ftlvariable name="showAnalyticsDashboard" type="boolean" --]
[#-- @ftlvariable name="spaTimeout" type="int" --]
[#-- @ftlvariable name="spaRefreshInterval" type="int" --]
[#-- @ftlvariable name="serverTimezoneUTCOffset" type="int" --]
[#-- @ftlvariable name="devMode" type="boolean" --]
[#-- @ftlvariable name="serverSiteUrls" type="java.lang.String" --]

[#-- @ftlvariable name="viewTitle" type="java.lang.String" --]
[#-- @ftlvariable name="meta" type="java.lang.String" --]
