// This file is automatically generated. Please do not change this file!
export const forwardIconWrapper: string;
export const moveStageToLeftRight: string;
export const stageBox: string;
export const stageBtnGroup: string;
export const stageContent: string;
export const stageNameHeader: string;
export const stageSettingsIconWrapper: string;
export const stagesBody: string;
export const stagesContainer: string;
export const stagesMainComponent: string;
