// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const button: string;
export const disabled: string;
export const btnSmall: string;
export const btnPrimary: string;
export const btnDanger: string;
export const btnSecondary: string;
export const btnReset: string;
export const btnCancel: string;
export const iconAdd: string;
export const iconDoc: string;
