// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const agentStatus: string;
export const buildDetails: string;
export const show: string;
export const agentCheckbox: string;
export const agentsTable: string;
export const tableCell: string;
export const building: string;
export const disabledAgent: string;
export const headerPanel: string;
export const count: string;
export const enabled: string;
export const disabled: string;
export const searchField: string;
