// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const agentStatus: string;
export const buildDetails: string;
export const show: string;
export const searchField: string;
export const agentCheckbox: string;
