// This file is automatically generated. Please do not change this file!
export const rotate: string;
export const testConnectionButtonWrapper: string;
export const testConnectionFailure: string;
export const testConnectionInProgress: string;
export const testConnectionResult: string;
export const testConnectionSuccess: string;
