// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const tree: string;
export const treeDatum: string;
export const treeChild: string;
export const treeChildren: string;
export const treeChildrenLabel: string;
export const loading: string;
export const group: string;
export const groupDatum: string;
export const environment: string;
export const environmentDatum: string;
export const pipeline: string;
export const pipelineDatum: string;
