// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const goodLastParseIcon: string;
export const lastParseErrorIcon: string;
export const neverParsed: string;
export const missingPluginIcon: string;
