// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const goodLastParseIcon: string;
export const lastParseErrorIcon: string;
export const neverParsed: string;
export const missingPluginIcon: string;
export const goodModificationIcon: string;
export const errorLastModificationIcon: string;
export const lastRevision: string;
export const lastRevisionValue: string;
export const statusIcon: string;
export const spinnerWrapper: string;
export const testConnectionResult: string;
export const testConnectionButtonWrapper: string;
export const pluginFilePatternConfigWrapper: string;
export const testConnectionSuccess: string;
export const testConnectionFailure: string;
export const testConnectionInProgress: string;
export const rotate: string;
export const configRepoUpdateInProgress: string;
export const materialConfigWrapper: string;
export const keyValueTitle: string;
export const headerTitleText: string;
export const parseErrorText: string;
export const wrapperForSearchBox: string;
export const configRepoErrorHeader: string;
export const configRepoProperties: string;
export const errorMessage: string;
