// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const isActive: string;
export const hide: string;
export const tabs: string;
export const tabHeaderContainer: string;
export const tabHeader: string;
export const tabContent: string;
