// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const tabs: string;
export const tabHead: string;
export const active: string;
export const tab_container: string;
export const tabContainer: string;
export const tab_content: string;
export const tabContent: string;
export const tabAccordionHeading: string;
export const hide: string;
