// This file is automatically generated. Please do not change this file!
export const addRule: string;
export const iconDelete: string;
export const infoIcon: string;
export const mappings: string;
export const names: string;
export const rulesTable: string;
export const rulesWrapper: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tips: string;
export const version: string;
export const warningContent: string;
export const warningWrapper: string;
export const widthSmall: string;
