#--
# DO NOT EDIT
# This file is auto-generated by build scripts.
# See:  rake update_version
#++

module Gem

  ##
  # The version of RubyGems you are using

  RubyGemsVersion = '1.3.3'

  ##
  # The version of RubyGems you are using (duplicated for familiarity)

  VERSION = RubyGemsVersion

end
