// This file is automatically generated. Please do not change this file!
export const bell: string;
export const hoverContainer: string;
export const mappings: string;
export const menu: string;
export const names: string;
export const notificationClose: string;
export const notificationHover: string;
export const notificationItem: string;
export const notification_close: string;
export const notification_item: string;
export const notifications: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const systemNotifications: string;
export const topBar: string;
export const version: string;
