// This file is automatically generated. Please do not change this file!
export const checkbox: string;
export const container: string;
export const pipelineStructure: string;
export const pipelineStructureHeader: string;
export const pipelineStructureWrapper: string;
export const profileForm: string;
export const searchFieldContainer: string;
export const selectPipelinesButtons: string;
