// This file is automatically generated. Please do not change this file!
export const jobStateTransitionInformationContainer: string;
export const key: string;
export const keyValuePair: string;
export const value: string;
