/*
 * Copyright Thoughtworks, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.thoughtworks.go.build.*

configurations {
  pluginsZipConfig
}

def dependencies = [
  new GithubArtifact(
    user: 'gocd',
    repo: 'gocd-ldap-authentication-plugin',
    tagName: 'v4.0.1-540',
    asset: 'gocd-ldap-authentication-plugin-4.0.1-540.jar',
    checksum: '8928076076e482342e3e1a65b56cef27e7bb7a3dc43d56e6a660990cbb3eee14'
  ),
  new GithubArtifact(
    user: 'gocd',
    repo: 'gocd-filebased-authentication-plugin',
    tagName: 'v3.0.1-423',
    asset: 'gocd-filebased-authentication-plugin-3.0.1-423.jar',
    checksum: '2a2bc460c4c642c8741dde5f474bbdeffff67633f9d0c3238b7537d081c0c2e3'
  ),
  new GithubArtifact(
    user: 'tomzo',
    repo: 'gocd-yaml-config-plugin',
    tagName: 'v2.1.0-547',
    asset: 'yaml-config-plugin-2.1.0-547.jar',
    checksum: '7c0b28205b963baec59a22a975bb89fb3fb0019b892198ce50978a8330a5958f'
  ),
  new GithubArtifact(
    user: 'tomzo',
    repo: 'gocd-json-config-plugin',
    tagName: 'v2.1.0-392',
    asset: 'json-config-plugin-2.1.0-392.jar',
    checksum: '18b8b46296b1a0d75241b3628ff8f17fa616c46a5e2b604e846416363dc7b357'
  ),
  new GithubArtifact(
    user: 'gocd',
    repo: 'gocd-file-based-secrets-plugin',
    tagName: 'v2.0.1-442',
    asset: 'gocd-file-based-secrets-plugin-2.0.1-442.jar',
    checksum: '72dad76eb1dd27951149ab4543b7137c6ced2899115698a0b7db63aea15879c1'
  )
]

tasks.register('createVersionFile') {
  def goVersions = rootProject.goVersions as GoVersions
  inputs.property('goVersions', goVersions)

  def file = layout.buildDirectory.file("version.txt").get().asFile
  outputs.file file

  doLast {
    file.getParentFile().mkdirs()
    file.withWriter { out ->
      out.write("${goVersions.fullVersion} (${goVersions.gitRevision})")
    }
  }
}

def downloadPlugins = tasks.register('downloadPlugins')

def pluginsZip = tasks.register('pluginsZip', Zip) {
  finalizedBy 'verifyPluginZip'

  archiveBaseName = 'plugins'
  dependsOn createVersionFile
  from(createVersionFile)

  from(dependencies.collect { dep -> destFile(dep) })
}

tasks.register('verifyPluginZip', VerifyJarTask) {
  jarTask = pluginsZip
  expectedJars = [
    '/': dependencies.collect { dep -> "${dep.repo}.jar".toString() }
  ]
}

artifacts {
  pluginsZipConfig pluginsZip
}

dependencies.each { dep ->
  def downloadTask = tasks.register("download-${dep.repo}", DownloadFile) { downloadTask ->
    downloadTask.src dep.downloadUrl
    downloadTask.dest destFile(dep)
    downloadTask.checksum = dep.checksum
  }

  downloadPlugins.configure {
    dependsOn downloadTask
  }

  pluginsZip.configure { Zip zipTask ->
    zipTask.dependsOn downloadTask
    zipTask.from(destFile(dep))
  }
}

private File destFile(GithubArtifact dep) {
  new File(gradle.gradleUserHomeDir, "download-cache/${TextUtils.md5Hex(dep.downloadUrl)}/${dep.repo}.jar")
}

tasks.register('prepare') { dependsOn pluginsZip }
