// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const footerWarningBanner: string;
export const footer: string;
export const left: string;
export const content: string;
export const right: string;
export const gocdVersion: string;
export const social: string;
export const twitter: string;
export const github: string;
export const forums: string;
export const plugins: string;
export const documentation: string;
export const cctray: string;
export const api: string;
export const serverDetails: string;
