// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const siteHeader: string;
export const mainNavigation: string;
export const gocd_logo: string;
export const gocdLogo: string;
export const siteNavigationLeft: string;
export const siteHeaderLeft: string;
export const siteHeaderRight: string;
export const navbtn: string;
export const bar: string;
export const animate: string;
export const need_help: string;
export const needHelp: string;
export const user: string;
export const isDropDown: string;
export const user_subnav: string;
export const userSubnav: string;
export const user_link: string;
export const userLink: string;
export const fa: string;
export const user_subnav_link: string;
export const userSubnavLink: string;
export const caret_down_icon: string;
export const caretDownIcon: string;
export const user_icon: string;
export const userIcon: string;
