// This file is automatically generated. Please do not change this file!
export const buttonContainer: string;
export const entityConfigContainer: string;
export const help: string;
export const mainContainer: string;
export const materialTab: string;
export const missingPlugin: string;
export const nameLink: string;
export const navigation: string;
export const radioLabelWithInlineTextfield: string;
export const steps: string;
