// This file is automatically generated. Please do not change this file!
export const entityConfigContainer: string;
export const entity_config_container: string;
export const mainContainer: string;
export const navigation: string;
