language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
jdk: # for JRuby only
  - openjdk7
  - oraclejdk8
matrix:
  exclude:
    - rvm: rbx-2
      jdk: oraclejdk8
    - rvm: 1.8.7
      jdk: oraclejdk8
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.0
      jdk: oraclejdk8