// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const foundationHax: string;
export const middle: string;
export const helpText: string;
export const inputGroup: string;
export const inputGroupLabel: string;
export const inputGroupField: string;
export const inputGroupButton: string;
export const fieldset: string;
export const isInvalidInput: string;
export const isInvalidLabel: string;
export const formError: string;
export const isVisible: string;
