// This file is automatically generated. Please do not change this file!
export const fieldset: string;
export const formError: string;
export const foundationFormHax: string;
export const foundationGridHax: string;
export const helpText: string;
export const inputGroup: string;
export const inputGroupButton: string;
export const inputGroupField: string;
export const inputGroupLabel: string;
export const isInvalidInput: string;
export const isInvalidLabel: string;
export const isVisible: string;
export const middle: string;
