// This file is automatically generated. Please do not change this file!
export const deprecationWarningIcon: string;
export const deprecationWarningTooltipContent: string;
export const deprecationWarningTooltipWrapper: string;
export const keyValuePairInline: string;
export const pluginHeader: string;
export const pluginIcon: string;
export const pluginName: string;
export const pluginsList: string;
export const pluginsPage: string;
export const spinnerWrapper: string;
export const unknownPluginIcon: string;
