// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const pluginHeader: string;
export const pluginIcon: string;
export const pluginName: string;
export const unknownPluginIcon: string;
export const pluginsPage: string;
export const keyValuePairInline: string;
export const pluginsList: string;
