version: 2
registries:
  gradle-plugins-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2/
updates:
  - package-ecosystem: gradle
    directory: /
    registries:
      - gradle-plugins-portal
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: /server/src/main/webapp/WEB-INF/rails
    commit-message:
      prefix: ui
      prefix-development: ui-dev
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 99
    groups:
      jasmine:
        patterns: [ "jasmine*", "@types/jasmine*" ]
      webpack:
        patterns: [ "webpack*", "*-loader", "*-webpack-plugin", "*mini-css-extract-plugin", "@babel/*" ]
      eslint:
        patterns: [ "eslint*", "@eslint/*", "@types/eslint*" ]
      types:
        patterns: [ "@types/*" ]
    ignore:
      - dependency-name: "angular"  # ignore vendored path based dependency
      - dependency-name: "opensans" # ignore vendored path based dependency
  - package-ecosystem: bundler
    directory: /server/src/main/webapp/WEB-INF/rails
    commit-message:
      prefix: ui
      prefix-development: ui-dev
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 99
    allow:
      - dependency-type: all
    groups:
      rails:
        patterns: [ "rail*", "active*", "action*" ]
      rack:
        patterns: [ "rack*" ]
      rspec:
        patterns: [ "rspec*" ]
      sass:
        patterns: [ "sass*" ]
    ignore:
      - dependency-name: "irb" # ignore locally vendored stub dependency
  - package-ecosystem: docker-compose
    directories:
      - "*"
    schedule:
      interval: weekly
      day: friday
