version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: milestone
        no_empty:
          enabled: true
          message: "Milestone must be specified"
        must_include:
          # one or more chars
          regex: '.+'
          message: "Milestone must be specified"
      - do: project
        must_include:
          regex: '\.+'
          message: "Project must be specified in the semvar versioning format. Example: 20.9.0"

    pass:
      - do: checks
        status: 'success'
