// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const overlay: string;
export const wizard: string;
export const wizardHeader: string;
export const wizardFooter: string;
export const wizardBody: string;
export const stepHeader: string;
export const selected: string;
export const stepBody: string;
