[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="repoName" type="java.lang.String" --]
[#-- @ftlvariable name="imageName" type="java.lang.String" --]
[#-- @ftlvariable name="copyrightYear" type="java.lang.String" --]
[#-- @ftlvariable name="project" type="org.gradle.api.Project" --]
[#-- @ftlvariable name="additionalFiles" type="java.util.Map<java.lang.String, java.util.Map<java.lang.String, java.lang.String>>" --]
[#-- @ftlvariable name="gitRevision" type="java.lang.String" --]
[#-- @ftlvariable name="fullVersion" type="java.lang.String" --]
[#-- @ftlvariable name="goVersion" type="java.lang.String" --]
[#-- @ftlvariable name="distro" type="com.thoughtworks.go.build.docker.Distro" --]
[#-- @ftlvariable name="distroVersion" type="com.thoughtworks.go.build.docker.DistroVersion" --]
