[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="imageName" type="java.lang.String" --]
[#-- @ftlvariable name="distro" type="com.thoughtworks.go.build.docker.Distro" --]
[#-- @ftlvariable name="distroVersion" type="com.thoughtworks.go.build.docker.DistroVersion" --]
[#-- @ftlvariable name="goVersions" type="com.thoughtworks.go.build.GoVersions" --]
[#-- @ftlvariable name="dockerAliasToWrapperArchAsShell" type="java.lang.String" --]
[#-- @ftlvariable name="useFromArtifact" type="boolean" --]
