Style/LeadingCommentSpace:
  Description: 'Comments should start with a space.'
  Enabled: false

Style/TrailingBlankLines:
  Description: 'Checks trailing blank lines and final newline.'
  Enabled: false

Metrics/LineLength: 
  Description: 'Limit lines to 200 characters.'
  Max: 200
  Enabled: true

Style/StringLiterals:
  Enabled: false
