#!/bin/bash
#*************************GO-LICENSE-START********************************
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*************************GO-LICENSE-END**********************************

set -e

LOCAL_BASE=${PKG_INSTALL_ROOT}$BASEDIR/go-server
LOCAL_WORK=${PKG_INSTALL_ROOT}/var/lib/go-server
LOCAL_LOG=${PKG_INSTALL_ROOT}/var/log/go-server
LOCAL_ETC=${PKG_INSTALL_ROOT}/etc

if [ ! -d ${LOCAL_ETC}/go ]; then
    mkdir ${LOCAL_ETC}/go
fi

[ -d ${LOCAL_LOG} ] || mkdir -p ${LOCAL_LOG}
[ -d ${LOCAL_WORK} ] || mkdir -p ${LOCAL_WORK}

# Create user and set directory permissions
grep '^go:' ${LOCAL_ETC}/passwd >/dev/null || useradd -c "Go User" -G daemon -m -d /var/go go

chown -R go:daemon ${LOCAL_ETC}/go
chown -R go:daemon ${LOCAL_LOG}

chown go:daemon ${LOCAL_WORK}

# Copy init script
cp -f ${LOCAL_BASE}/go-server ${PKG_INSTALL_ROOT}/lib/svc/method

echo "Installation of Go Server completed."

# Register the service (starts it up as well)
svccfg import ${LOCAL_BASE}/svc.xml

