// This file is automatically generated. Please do not change this file!
export const currentPage: string;
export const disabled: string;
export const mappings: string;
export const names: string;
export const paginationContainer: string;
export const paginationLink: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
