// This file is automatically generated. Please do not change this file!
export const currentPage: string;
export const disabled: string;
export const paginationContainer: string;
export const paginationLink: string;
