// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const progressConsoleContainer: string;
export const message: string;
export const error: string;
