// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const drainModeWidget: string;
export const drainModeDescription: string;
export const drainModeInfo: string;
export const inProgressSubsystems: string;
export const panel: string;
export const panelHeader: string;
export const panelBody: string;
export const runningSystemHeader: string;
export const col2: string;
export const col: string;
