// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const drainModeWidget: string;
export const drainModeDescription: string;
export const runningSystem: string;
export const runningSystemText: string;
export const updatedBy: string;
export const switchWrapper: string;
export const drainModeLabel: string;
export const drainModeStateMessage: string;
export const inProgressSubsystems: string;
export const runningSubSystem: string;
export const gocdSubSystemInfo: string;
export const panel: string;
export const panelHeader: string;
export const panelBody: string;
export const runningSystemHeader: string;
