// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const spinnerWrapper: string;
export const tag: string;
export const currentUserTag: string;
export const colorEffect: string;
export const roleUserDeleteIcon: string;
export const disabled: string;
export const addUserToRole: string;
export const usersInRole: string;
