// This file is automatically generated. Please do not change this file!
export const active: string;
export const buttons: string;
export const deleteIcon: string;
export const formContainer: string;
export const formFields: string;
export const formHeader: string;
export const leftPanel: string;
export const purgeSettingsFields: string;
export const rightPanel: string;
export const serverConfigurationContainer: string;
