source 'http://rubygems.org'

gem 'rails', '~> 2.3.5'

gem 'validatable', '1.6.7'
gem 'multi_json', '1.0.0'
gem 'json'

group :test do
  gem 'rspec', '1.2.8'
  gem 'rspec-rails', '1.2.7.1'
  gem 'selenium-webdriver', '2.35.1'

  # Incompatible with rspec (requires at least 1.3.1)
  # gem 'jasmine', '1.3.2'
  # gem 'jasmine-core', '1.3.1'
end