// This file is automatically generated. Please do not change this file!
export const advancedSettings: string;
export const details: string;
export const lockOpen: string;
export const open: string;
export const summary: string;
