// This file is automatically generated. Please do not change this file!
export const cancelButtonWrapper: string;
export const iconDelete: string;
export const lightColor: string;
export const parent: string;
export const permissionCheckboxWrapper: string;
export const permissionNameWrapper: string;
export const propertiesWrapper: string;
export const stageJobTree: string;
export const stageOrJob: string;
export const switchWrapper: string;
export const taskDescription: string;
export const taskList: string;
export const taskRow: string;
export const taskRunIf: string;
