// This file is automatically generated. Please do not change this file!
export const lightColor: string;
export const parent: string;
export const propertiesWrapper: string;
export const stageJobTree: string;
export const stageOrJob: string;
export const taskDescription: string;
export const taskList: string;
export const taskRow: string;
export const taskRunIf: string;
