// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const tooltipWrapper: string;
export const tooltipContent: string;
export const small: string;
export const medium: string;
export const large: string;
