// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const btnIcon: string;
export const disabled: string;
export const settings: string;
export const analytics: string;
export const edit: string;
export const clone: string;
export const remove: string;
export const lock: string;
export const close: string;
export const question: string;
export const check: string;
export const spinner: string;
export const spin: string;
export const refresh: string;
export const usage: string;
export const minus: string;
export const infoCircle: string;
export const infoTooltip: string;
export const questionCircle: string;
export const helpTooltip: string;
export const iconGroup: string;
export const tooltiptext: string;
export const small: string;
export const medium: string;
export const large: string;
