#!/usr/bin/env ruby
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.  The ASF
# licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.


# Run buildr from source, specifically for testing stuff without doing a rake install.

require 'rubygems'
$LOAD_PATH << File.join(File.dirname(__FILE__), 'lib') << File.join(File.dirname(__FILE__), 'addon')

require 'buildr/version'
spec = Gem::Specification.load(File.join(File.dirname(__FILE__), 'buildr.gemspec'))
# To avoid a warning about the version_requirements deprecation, we use this method inline.
def version_required(gem_def)
  return Gem::Dependency.instance_methods.map(&:to_sym).include?(:requirement) ? gem_def.requirement : gem_def.version_requirements
end
spec.dependencies.each do |dep|
  gem dep.name, version_required(dep).to_s if dep.type == :runtime
end
Gem.loaded_specs['buildr'] = spec # Prevents RubyGem from loading files from installed Buildr gems

require 'buildr'
Buildr.application.run
