// This file is automatically generated. Please do not change this file!
export const h1: string;
export const h2: string;
export const h3: string;
export const h4: string;
export const h5: string;
export const h6: string;
export const listUnstyled: string;
export const mainContainer: string;
export const page: string;
export const pagewrap: string;
export const sitefooter: string;
