// This file is automatically generated. Please do not change this file!
export const mainContainer: string;
export const page: string;
export const pagewrap: string;
export const sitefooter: string;
