// This file is automatically generated. Please do not change this file!
export const additional: string;
export const leadIn: string;
export const open: string;
export const showMoreDoc: string;
export const toggle: string;
