// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const notifications: string;
export const hoverContainer: string;
export const bell: string;
export const notificationHover: string;
export const notification_item: string;
export const notificationItem: string;
export const notification_close: string;
export const notificationClose: string;
export const systemNotifications: string;
export const topBar: string;
export const menu: string;
