#
# Copyright Thoughtworks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Some monkey patching for fixing the url prefix
module TsRoutesExt
  def build_route_function(*args)
    super.gsub(/ return /, ' return "/go" + ')
  end
end

TsRoutes::Generator.send(:prepend, TsRoutesExt)

# Joins chunks like successive `puts` calls would: each chunk gets a trailing newline unless it already has one
def as_lines(*chunks)
  chunks.map { |chunk| chunk.to_s.sub(/\n?\z/, "\n") }.join
end

# Only touch files whose content actually changed, so that mtime-based watchers (webpack --watch)
# are not triggered by regeneration of identical content
def write_if_changed(path, content)
  return if File.exist?(path) && File.read(path) == content

  File.write(path, content)
end

task generated_js: :environment do
  %w[OUTPUT_DIR GOCD_VERSION GOCD_DIST_VERSION GOCD_GIT_SHORT_REVISION].each do |var|
    raise "#{var} not set" if ENV[var].blank?
  end
  mkdir_p ENV['OUTPUT_DIR']

  write_if_changed(Rails.root.join("#{ENV['OUTPUT_DIR']}/js-routes.js"), as_lines(
    "// This file is automatically generated by `generated_js` task. Any changes will be lost",
    "/* eslint-disable */",
    JsRoutes.generate
  ))

  write_if_changed(Rails.root.join("#{ENV['OUTPUT_DIR']}/ts-routes.ts"), as_lines(
    "// This file is automatically generated by `generated_js` task. Any changes will be lost",
    "/* tslint:disable */",
    TsRoutes.generate(include: JsRoutes.configuration.include)
  ))

  write_if_changed(Rails.root.join("#{ENV['OUTPUT_DIR']}/gocd_version.ts"), as_lines(
    "// This file is automatically generated by `generated_js` task. Any changes will be lost",
    "/* tslint:disable */",
    "export const GoCDVersion = " + JSON.pretty_generate({
      "version" => ENV['GOCD_VERSION'],
      "distVersion" => ENV['GOCD_DIST_VERSION'],
      "gitShortRevision" => ENV['GOCD_GIT_SHORT_REVISION']
    }),
    "
      function stripLeadingPrefix(suffix: string, prefix: string) {
        if (suffix.startsWith(prefix)) {
            suffix = suffix.substring(1);
        }
        return suffix;
      }

      export function docsUrl(suffix: string = '') {
        return `https://docs.gocd.org/#{ENV['GOCD_VERSION']}/${stripLeadingPrefix(suffix, '/')}`
      }

      export function apiDocsUrl(suffix: string = '') {
        return `https://api.gocd.org/#{ENV['GOCD_VERSION']}/${stripLeadingPrefix(suffix, '#')}`
      }
    ".strip_heredoc
  ))
end
