// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const mainMenu: string;
export const siteNav: string;
export const siteNavItem: string;
export const active: string;
export const isDropDown: string;
export const subNavigation: string;
export const caret_down_icon: string;
export const caretDownIcon: string;
export const siteNavLink: string;
export const siteSubNav: string;
export const siteSubNavLinkHead: string;
export const siteSubNavItem: string;
export const siteSubNavLink: string;
