// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const tree: string;
export const treeDatum: string;
export const treeChild: string;
export const treeChildren: string;
export const treeChildrenLabel: string;
