// This file is automatically generated. Please do not change this file!
export const building: string;
export const cancelled: string;
export const failed: string;
export const failing: string;
export const passed: string;
export const stage: string;
export const stagesContainer: string;
export const unknown: string;
