// This file is automatically generated. Please do not change this file!
export const building: string;
export const cancelled: string;
export const clickable: string;
export const failed: string;
export const failing: string;
export const mappings: string;
export const names: string;
export const passed: string;
export const pipelineInstanceCounter: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const stage: string;
export const stagesContainer: string;
export const unknown: string;
export const version: string;
