// This file is automatically generated. Please do not change this file!
export const cDownArrow: string;
export const cDropdown: string;
export const cDropdownBody: string;
export const cDropdownHead: string;
export const cDropdownItem: string;
export const groupby: string;
export const groupingLabel: string;
export const grouping_label: string;
export const open: string;
