// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const panel: string;
export const panel_header: string;
export const panelHeader: string;
export const header_details: string;
export const headerDetails: string;
export const panel_body: string;
export const panelBody: string;
export const actions: string;
