// This file is automatically generated. Please do not change this file!
export const availableDiskSpace: string;
export const backupConfigHelp: string;
export const backupContainer: string;
export const backupHelp: string;
export const backupInfo: string;
export const backupLocation: string;
export const content: string;
export const helpHeading: string;
export const helpItem: string;
export const performBackupButtonContainer: string;
export const performBackupContainer: string;
export const performBackupSection: string;
