// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const formHeader: string;
export const formGroup: string;
export const formLabel: string;
export const formLabelRequired: string;
export const formControl: string;
export const inline: string;
export const formInputReset: string;
export const textArea: string;
export const formHelp: string;
export const formErrorText: string;
export const formHasError: string;
export const form: string;
export const formResponsive: string;
export const searchBoxWrapper: string;
export const searchBoxInput: string;
