// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const formGroup: string;
export const formLabel: string;
export const formControl: string;
export const textArea: string;
export const formHelp: string;
export const formErrorText: string;
export const formHasError: string;
