// This file is automatically generated. Please do not change this file!
export const arrowRight: string;
export const behaviorPrompt: string;
export const mappings: string;
export const names: string;
export const small: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
