// This file is automatically generated. Please do not change this file!
export const arrowDown: string;
export const arrowLeft: string;
export const arrowRight: string;
export const arrowUp: string;
export const behaviorPrompt: string;
export const medium: string;
export const small: string;
