// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const maintenanceModeWidget: string;
export const maintenanceModeDescription: string;
export const maintenanceModeInfo: string;
export const runningSystem: string;
export const runningSystemText: string;
export const updatedBy: string;
export const switchWrapper: string;
export const maintenanceModeLabel: string;
export const maintenanceModeStateMessage: string;
export const inProgressSubsystems: string;
export const runningSubSystem: string;
export const gocdSubSystemInfo: string;
export const panel: string;
export const panelHeader: string;
export const panelBody: string;
export const runningSystemHeader: string;
export const scheduledStagesTitleWrapper: string;
export const scheduledStagesTitle: string;
