// This file is automatically generated. Please do not change this file!
export const clickable: string;
export const overlay: string;
export const selected: string;
export const stepBody: string;
export const stepHeader: string;
export const wizard: string;
export const wizardBody: string;
export const wizardFooter: string;
export const wizardHeader: string;
