// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const table: string;
export const sortableColumn: string;
export const sortButton: string;
export const inActive: string;
