// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const wrapper: string;
export const ellipsisActionButton: string;
export const fixEllipsized: string;
