source 'https://rubygems.org'

gem 'rails', '4.0.4'

gem 'validatable', '>=1.6.0'

gem 'dynamic_form'

gem 'gadgets', '0.0.1', path: 'vendor/engines/gadgets'

gem 'sprockets-rails'
gem 'sass-rails'
gem 'requirejs-rails'
gem 'mithril_rails'
gem 'uglifier'
gem 'foundation-rails'
gem 'bourbon'
gem 'font-awesome-sass'
gem 'js-routes'

gem 'oauth2_provider', '1.0.3', path: 'vendor/engines/oauth2_provider'
gem 'versionist'
gem 'roar'

group :development, :test do
  gem 'rails-dev-tweaks', '~> 1.1'
  gem 'minitest'
  gem "jasmine"
  gem "jasmine-rails"
  gem 'selenium-webdriver'
  gem 'jasmine-jquery-rails'
  gem 'jasmine-junitreporter'

  gem 'rspec-rails', '2.14.2'
  gem 'rspec-extra-formatters'

  gem 'capybara', '2.2.1'
  gem 'ruby-debug-base', '0.10.5.rc10'
  gem 'ruby-debug-ide', '0.4.30'
end
