# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
STDERR.sync = true
STDOUT.sync = true
at_exit do
  STDOUT.flush
  STDERR.flush
  sleep 0.1
end
require File.expand_path('../config/application', __FILE__)

Go::Application.load_tasks
