// This file is automatically generated. Please do not change this file!
export const disabled: string;
export const inProgress: string;
export const isSuccess: string;
export const switchBtn: string;
export const switchInput: string;
export const switchLabel: string;
export const switchPaddle: string;
export const switchSmall: string;
export const switchWrapper: string;
