// This file is automatically generated. Please do not change this file!
export const fillable: string;
export const mappings: string;
export const multiSection: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const subSection: string;
export const version: string;
