// This file is automatically generated. Please do not change this file!
export const args: string;
export const caveats: string;
export const cmd: string;
export const comment: string;
export const currentEditor: string;
export const errors: string;
export const execEditor: string;
export const hasErrors: string;
export const helpBody: string;
export const helpContent: string;
export const helpHeader: string;
export const mod: string;
export const open: string;
export const task: string;
