// This file is automatically generated. Please do not change this file!
export const attention: string;
export const constrained: string;
export const sectionHeading: string;
export const sectionNote: string;
export const sectionSubheading: string;
export const userInput: string;
