// This file is automatically generated. Please do not change this file!
export const args: string;
export const caveats: string;
export const cmd: string;
export const comment: string;
export const currentEditor: string;
export const execEditor: string;
export const open: string;
export const task: string;
