// This file is automatically generated. Please do not change this file!
export const externalIcon: string;
export const inlineLink: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
