// This file is automatically generated. Please do not change this file!
export const environment: string;
export const environmentDatum: string;
export const group: string;
export const groupDatum: string;
export const loading: string;
export const pipeline: string;
export const pipelineDatum: string;
export const rotate: string;
export const selected: string;
export const spin: string;
export const tree: string;
export const treeChild: string;
export const treeChildren: string;
export const treeChildrenLabel: string;
export const treeDatum: string;
