name: Bug Report
description: File a bug report to help us improve GoCD
labels: []
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        *Security issue?* Please **DO NOT** report it here. Use [hackerone](https://hackerone.com/gocd) to report security vulnerabilities.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a brief summary of the issue.
    validations:
      required: true

  - type: textarea
    id: environment-basic
    attributes:
      label: Environment
      description: |
        Describe the environment in which you encountered this issue. Most can be obtained from [/go/about](https://go-server-host:port/go/about)
      value: |
        ### Basic Details:
        - *Go Server Version*: 
        - *JVM Version*: 
        - *OS Information*: 
        
        ### Additional Details _(if relevant)_:
        - *Browser vendor/version*:
        - *Relevant plugins in use*:
        
        ### Deployment mechanism _(e.g. static vs elastic, Docker, Kubernetes, RPM package etc)_
        - *Go Server*:
        - *Go Agent(s)*:
    validations:
      required: true

  - type: textarea
    id: environment-support
    attributes:
      label: Support Environment
      description: |
        The most effective support can be given if you fetch details as a logged-in admin from the GoCD support API 
        at [/go/api/support](https://go-server-host:port/go/api/support) via a browser. You can redact confidential 
        information from the response, but please leave structure intact. If redacting, pay attention to the system properties, 
        environment variables and server health messages.
      placeholder: |
        Paste the (potentially redacted) JSON output from /go/api/support here.
      render: json

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide an unambiguous set of steps to reproduce this bug, as best you can.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: actual-results
    attributes:
      label: Actual Results
      description: Tell us what actually happened.
    validations:
      required: true

  - type: textarea
    id: expected-results
    attributes:
      label: Expected Results
      description: Tell us what you expected to happen instead.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Optional Additional details

  - type: textarea
    id: logs
    attributes:
      label: Log snippets
      description: Please provide any relevant information or exceptions from the logs. Mask/redact confidential information.
      value: |
        ```
        <paste relevant log snippets here>
        ```

  - type: textarea
    id: possible-fix
    attributes:
      label: Possible Fix
      description: Not obligatory, but suggest a fix or reason for the bug.

  - type: textarea
    id: other-info
    attributes:
      label: Any other info
      description: Provide any other information you would like to share.
