# Additional suppressions for issues detected by Trivy that are not found by OWASP dependency check

vulnerabilities:
  - id: CVE-2024-38819
    statement: >
      GoCD does not seem to be affected as does not use the functional Spring web frameworks/RouterFunctions per
      https://spring.io/security/cve-2024-38819
      org.springframework:spring-webmvc (go.jar) Fixed: 6.1.14
      https://avd.aquasec.com/nvd/cve-2024-38819 
  - id: CVE-2024-38821
    statement: >
      According to https://spring.io/security/cve-2024-38821 this only affects WebFlux applications which GoCD is not.
      org.springframework.security:spring-security-web (go.jar) Fixed: 5.7.13, 5.8.15, 6.2.7, 6.0.13, 6.1.11, 6.3.4
      https://avd.aquasec.com/nvd/cve-2024-38821
  - id: CVE-2026-22732
    statement: >
      After review of https://spring.io/security/cve-2026-22732 it doesn't appear GoCD is affected by this issue. It
      only seems to happen in cases where Spring Framework writes content length headers early and directly to the response
      (without buffering in HttpHeaders as in earlier versions), and Spring Security is needed to write headers directly
      to the response. The change in Spring FW highlighted an old Spring Security bug to do with content length handling,
      causing some response headers to be lost. While the root issue is within Spring Security and similar code exists
      in our version, since we are using an old Spring Web + Spark + jruby-rack AND we do not rely on Spring Security to
      write response headers (we still have a custom DefaultHeadersFilter) it seems unlikely GoCD can be affected. See
      https://github.com/spring-projects/spring-security/issues/18797 and https://github.com/spring-projects/spring-framework/issues/36381#issuecomment-3953118692
      for some more detail.
      org.springframework.security:spring-security-web (go.jar) Fixed: 6.5.9, 7.0.4
      https://avd.aquasec.com/nvd/cve-2026-22732
  # Leave whitespace at the end of the file for appending suppressions from OWASP dependency check :-)
  # Augment to this file with
  # grep -oE '<(cve|vulnerabilityName)>(CVE|GHSA).*</(cve|vulnerabilityName)>' build-platform/dependency-check-suppress.xml | sed -E 's/<(cve|vulnerabilityName)>(.*)<\/(cve|vulnerabilityName)>/  - id: \2/' >> build-platform/.trivyignore.yaml
