# Additional suppressions for issues detected by Trivy that are not found by OWASP dependency check

vulnerabilities:
  - id: CVE-2024-6763
    purls:
      - pkg:maven/org.eclipse.jetty/jetty-http@10.0.26
    statement: >
      False positive as this was actually fixed in 10.0.x, however while GoCD does use the HttpURI class directly, 
      it does not parse authority names from this, it only reconstructs a URL with the entire URI portion in tact, 
      while modifying the path to remove a prefix and support routing to Rails-handled code.
      org.eclipse.jetty:jetty-http (go.jar) Fixed: 12.0.12
      https://avd.aquasec.com/nvd/cve-2024-6763/
  - id: CVE-2024-38819
    purls:
      - pkg:maven/org.springframework/spring-webmvc@4.3.30.RELEASE
    statement: >
      GoCD does not seem to be affected as does not use the functional Spring web frameworks/RouterFunctions per
      https://spring.io/security/cve-2024-38819
      org.springframework:spring-webmvc (go.jar) Fixed: 6.1.14
      https://avd.aquasec.com/nvd/cve-2024-38819
  - id: CVE-2026-8763
    purls:
      - pkg:maven/org.bouncycastle:bcprov-jdk18on@1.84
    statement: >
      Embedded within JRuby 9.4.15.0; GoCD does not rely on jruby-openssl. Remove suppression after 10.0.7.0 upgrade.
  - id: CVE-2026-13506
    purls:
      - pkg:maven/org.bouncycastle:bcprov-jdk18on@1.84
    statement: >
      Embedded within JRuby 9.4.15.0; GoCD does not rely on jruby-openssl. Remove suppression after 10.0.7.0 upgrade.
  - id: CVE-2026-85091
    expired_at: 2026-10-10
    statement: >
      There is no fix available for this issue at this time, see https://github.com/madler/zlib/issues/1310
  # Leave whitespace at the end of the file for appending suppressions from OWASP dependency check :-)
  # Augment to this file with
  # grep -oE '<(cve|vulnerabilityName)>(CVE|GHSA).*</(cve|vulnerabilityName)>' build-platform/dependency-check-suppress.xml | sed -E 's/<(cve|vulnerabilityName)>(.*)<\/(cve|vulnerabilityName)>/  - id: \2/' >> build-platform/.trivyignore.yaml
