// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const materialCheckResult: string;
export const materialConfigFiles: string;
export const resultsTitle: string;
export const pluginConfigFiles: string;
export const materialCheckFile: string;
export const materialCheckButtonWrapper: string;
export const materialCheckSuccess: string;
export const materialCheckFailure: string;
export const materialCheckInProgress: string;
export const rotate: string;
