// This file is automatically generated. Please do not change this file!
export const configFilesErrors: string;
export const fileList: string;
export const materialCheckContainer: string;
export const materialCheckControl: string;
export const materialCheckFailure: string;
export const materialCheckFile: string;
export const materialCheckInProgress: string;
export const materialCheckMessage: string;
export const materialCheckResult: string;
export const materialCheckSuccess: string;
export const materialConfigFiles: string;
export const pluginConfigFiles: string;
export const pluginLabel: string;
export const resultsTitle: string;
export const rotate: string;
