// This file is automatically generated. Please do not change this file!
export const commandSection: string;
export const deleteTaskWrapper: string;
export const execEditor: string;
export const execTaskDescriptionContainer: string;
export const runIfConditionsWrapper: string;
export const selectedTask: string;
export const taskDescriptionContainer: string;
export const taskItem: string;
export const taskItemWrapper: string;
export const tasksContainer: string;
export const tasksListContainer: string;
