// This file is automatically generated. Please do not change this file!
export const errorBox: string;
export const loggedOut: string;
export const loginButton: string;
export const loginContainer: string;
export const loginForm: string;
export const loginFormFields: string;
export const loginGraphics: string;
export const loginInput: string;
export const loginMethods: string;
export const loginOptions: string;
export const loginUser: string;
export const logoutGraphics: string;
export const otherLoginMethods: string;
export const redirect: string;
export const webLoginLink: string;
