// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const loginButtonWrapper: string;
export const loginForm: string;
export const loginGraphics: string;
export const loginMethods: string;
export const loginUser: string;
export const loginFormFields: string;
export const loginInput: string;
export const otherLoginMethods: string;
export const loginOptions: string;
export const webLoginLink: string;
export const redirect: string;
export const loggedOut: string;
export const logoutGraphics: string;
export const errorBox: string;
