// This file is automatically generated. Please do not change this file!
export const addPermission: string;
export const addUserToRole: string;
export const colorEffect: string;
export const currentUserTag: string;
export const disabled: string;
export const iconDelete: string;
export const infoIcon: string;
export const noUsersMessage: string;
export const roleUserDeleteIcon: string;
export const selectPermission: string;
export const spinnerWrapper: string;
export const tag: string;
export const tips: string;
export const usersInRole: string;
export const warningContent: string;
export const warningWrapper: string;
