services:
  trivy:
    image: docker.io/aquasec/trivy:0.69.3@sha256:bcc376de8d77cfe086a917230e818dc9f8528e3c852f7b1aff648949b6258d1c
    command: [ image, --input, /scan-image, --exit-code, "${EXIT_CODE_ON_ERROR}", --config, /trivy.yaml ]
    volumes:
      - ./trivy.yaml:/trivy.yaml:ro
      - trivycache:/root/.cache
volumes:
  trivycache:
