services:
  trivy:
    image: docker.io/aquasec/trivy:0.69.2@sha256:3d1f862cb6c4fe13c1506f96f816096030d8d5ccdb2380a3069f7bf07daa86aa
    entrypoint: trivy
    command: [
      image,
      --input, /scan-image,
      --no-progress,
      --skip-version-check,
      --disable-telemetry,
      --scanners, "vuln,misconfig,secret",
      --ignorefile, "/.trivyignore.yaml",
      --ignore-status, "not_affected,under_investigation,will_not_fix",
      --exit-code, "${EXIT_CODE_ON_ERROR}"
    ]
    volumes:
      - trivycache:/root/.cache
volumes:
  trivycache:
