services:
  trivy:
    image: docker.io/aquasec/trivy:0.70.0@sha256:be1190afcb28352bfddc4ddeb71470835d16462af68d310f9f4bca710961a41e
    command: [ image, --input, /scan-image, --exit-code, "${EXIT_CODE_ON_ERROR}", --config, /trivy.yaml ]
    volumes:
      - ./trivy.yaml:/trivy.yaml:ro
      - trivycache:/root/.cache
volumes:
  trivycache:
