// This file is automatically generated. Please do not change this file!
export const additional: string;
export const leadIn: string;
export const mappings: string;
export const names: string;
export const open: string;
export const showMoreDoc: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const toggle: string;
export const version: string;
