// This file is automatically generated. Please do not change this file!
export const active: string;
export const hide: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tabAccordionHeading: string;
export const tabContainer: string;
export const tabContent: string;
export const tabHead: string;
export const tab_container: string;
export const tab_content: string;
export const tabs: string;
export const version: string;
