// This file is automatically generated. Please do not change this file!
export const iconGroupWrapper: string;
export const mappings: string;
export const names: string;
export const noPipelinesDefinedMessage: string;
export const pipelineActionButtons: string;
export const pipelineGroupActionButtons: string;
export const pipelineGroupName: string;
export const pipelineGroupRow: string;
export const pipelineName: string;
export const pipelineRow: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tips: string;
export const value: string;
export const version: string;
