// This file is automatically generated. Please do not change this file!
export const cancelButtonWrapper: string;
export const errors: string;
export const iconDelete: string;
export const mappings: string;
export const names: string;
export const permissionCheckboxWrapper: string;
export const permissionNameWrapper: string;
export const pipelineGroupNameWrapper: string;
export const pipelineGroupTooltipWrapper: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
