// This file is automatically generated. Please do not change this file!
export const iconDelete: string;
export const pipelineGroupNameWrapper: string;
export const pipelineGroupTooltipWrapper: string;
export const usersPermissionTableDiv: string;
