// This file is automatically generated. Please do not change this file!
export const cancelButtonWrapper: string;
export const iconDelete: string;
export const permissionCheckboxWrapper: string;
export const permissionNameWrapper: string;
export const pipelineGroupNameWrapper: string;
export const pipelineGroupTooltipWrapper: string;
