// This file is automatically generated. Please do not change this file!
export const expanded: string;
export const expandedIconWrapper: string;
export const groupCheckbox: string;
export const pipelineCheckbox: string;
export const pipelineFilterWrapper: string;
export const pipelineGroupWrapper: string;
export const pipelineGroupsWrapper: string;
export const pipelinesWrapper: string;
