// This file is automatically generated. Please do not change this file!
export const allPipelinesWrapper: string;
export const header: string;
export const link: string;
export const pipelineCheckbox: string;
export const pipelineFilterWrapper: string;
export const pipelinesContainer: string;
export const searchFieldWrapper: string;
