// This file is automatically generated. Please do not change this file!
export const key: string;
export const keyValueInlineItem: string;
export const keyValueItem: string;
export const keyValuePair: string;
export const keyValuePairInline: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const title: string;
export const titleInline: string;
export const value: string;
export const version: string;
