// This file is automatically generated. Please do not change this file!
export const key: string;
export const keyValueInlineItem: string;
export const keyValueItem: string;
export const keyValuePair: string;
export const keyValuePairInline: string;
export const title: string;
export const titleInline: string;
export const value: string;
