// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const description: string;
export const revoked: string;
export const accessTokenSearchBox: string;
export const personalAccessTokenContainer: string;
export const activeTokensTable: string;
export const revokedTokensTable: string;
export const adminAccessTokenContainer: string;
export const spinnerContainer: string;
