// This file is automatically generated. Please do not change this file!
export const autocompleteInputContainer: string;
export const awesomplete: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
export const visuallyHidden: string;
