// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const rewardBanner: string;
export const slideFromUnder: string;
export const hide: string;
