// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const testConnectionResult: string;
export const testConnectionButtonWrapper: string;
export const testConnectionSuccess: string;
export const testConnectionFailure: string;
export const testConnectionInProgress: string;
export const rotate: string;
