// This file is automatically generated. Please do not change this file!
export const mappings: string;
export const names: string;
export const runIfCheckboxWrapper: string;
export const runIfConditionHelpText: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
