#-*- mode: ruby -*-

gemspec

# just make sure the openssl jar is in place
jar 'org.jruby:openssl', "#{model.version.sub(/.dev/, '')}-SNAPSHOT", :scope => :provided

properties( 'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true )

# vim: syntax=Ruby
