// This file is automatically generated. Please do not change this file!
export const helpTextWrapper: string;
export const key: string;
export const keyValuePair: string;
export const keyValuePairs: string;
export const mappings: string;
export const names: string;
export const pageHeader: string;
export const pageTitle: string;
export const page_title: string;
export const sectionName: string;
export const sectionWrapper: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const title: string;
export const value: string;
export const version: string;
