// This file is automatically generated. Please do not change this file!
export const pageHeader: string;
export const pageTitle: string;
export const page_title: string;
export const sectionName: string;
export const title: string;
