// This file is automatically generated. Please do not change this file!
export const helpTextWrapper: string;
export const key: string;
export const keyValuePair: string;
export const keyValuePairs: string;
export const pageHeader: string;
export const pageTitle: string;
export const page_title: string;
export const sectionName: string;
export const sectionWrapper: string;
export const title: string;
export const value: string;
