// This file is automatically generated. Please do not change this file!
export const count: string;
export const countWrapper: string;
export const green: string;
export const mappings: string;
export const names: string;
export const red: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
