approvedGitRepositories:
  - https://github.com/dtabuenc/karma-html-reporter.git

enableGlobalCache: true

enableScripts: false

enableTelemetry: false

npmMinimalAgeGate: "2d"

nodeLinker: node-modules
