source 'https://rubygems.org'
ruby '~> 3.1.0'

platforms :jruby do
  gem 'rails', '~> 7.2.0'
  gem 'sprockets-rails'
  gem 'rack', '~> 2.2.0' # For jruby-rack compatibility
  gem 'psych', '= 5.3.0' # For jruby 9.4.14 comaptibility
  gem 'irb', '~> 1.16.0'  # irb 1.17 brings in prism, which seems to reuqire/create native code

  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

  group :assets do
    gem 'dartsass-sprockets'
    gem 'js-routes', '~> 1.4'
    gem 'ts_routes'
  end

  group :test do
    gem 'capybara'
    gem 'rspec-rails'
    gem 'rspec_junit_formatter'
    gem 'rails-controller-testing'
  end
end
