source 'https://rubygems.org'
ruby '~> 3.1.0'

plugin 'bundler-override', '~> 0.2.0'
require File.join(Bundler::Plugin.index.load_paths("bundler-override")[0], "bundler-override") rescue nil

platforms :jruby do
  gem 'rails', '~> 7.2.0'; override 'railties', :drop => ['irb']
  gem 'sprockets-rails'
  gem 'rack', '~> 2.2.0' # For jruby-rack 1.2.x compatibility

  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

  group :assets do
    gem 'dartsass-sprockets'
    gem 'js-routes', '~> 1.4'
    gem 'ts_routes'
  end

  group :test do
    gem 'capybara'
    gem 'rspec-rails'
    gem 'rspec_junit_formatter'
    gem 'rails-controller-testing'
  end
end
