// This file is automatically generated. Please do not change this file!
export const accessTokenSearchBox: string;
export const activeTokensTable: string;
export const adminAccessTokenContainer: string;
export const description: string;
export const personalAccessTokenContainer: string;
export const revoked: string;
export const revokedTokensTable: string;
export const spinnerContainer: string;
export const tips: string;
