// This file is automatically generated. Please do not change this file!
export const accessTokenSearchBox: string;
export const activeTokensTable: string;
export const adminAccessTokenContainer: string;
export const description: string;
export const mappings: string;
export const names: string;
export const personalAccessTokenContainer: string;
export const revoked: string;
export const revokedTokensTable: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const spinnerContainer: string;
export const tips: string;
export const version: string;
