// This file is automatically generated. Please do not change this file!
export const configurationDetails: string;
export const configurationDetailsContainer: string;
export const configurationDetailsHeader: string;
export const expanded: string;
export const mappings: string;
export const names: string;
export const packageRepositoryCrudActions: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tips: string;
export const version: string;
export const warning: string;
