// This file is automatically generated. Please do not change this file!
export const configurationDetails: string;
export const configurationDetailsContainer: string;
export const configurationDetailsHeader: string;
export const expanded: string;
export const packageRepositoryCrudActions: string;
export const tips: string;
