// This file is automatically generated. Please do not change this file!
export const clipButton: string;
export const copied: string;
export const iconCheck: string;
export const iconClip: string;
export const iconCopy: string;
export const iconEllipsis: string;
export const iconFail: string;
export const mappings: string;
export const names: string;
export const snipNClip: string;
export const snippet: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
