// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const groupby: string;
export const grouping_label: string;
export const groupingLabel: string;
export const cDropdown: string;
export const cDropdownBody: string;
export const open: string;
export const cDropdownHead: string;
export const cDropdownItem: string;
export const cDownArrow: string;
