// This file is automatically generated. Please do not change this file!
export const button: string;
export const closeIcon: string;
export const errorWrapper: string;
export const extraLargeHackForEaProfiles: string;
export const fixed: string;
export const large: string;
export const medium: string;
export const modalBodyOverlay: string;
export const overlay: string;
export const overlayBg: string;
export const overlayClose: string;
export const overlayContent: string;
export const overlayFooter: string;
export const overlayHeader: string;
export const small: string;
export const spinnerWrapper: string;
