// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const overlay: string;
export const small: string;
export const medium: string;
export const large: string;
export const extraLargeHackForEaProfiles: string;
export const overlayHeader: string;
export const overlayClose: string;
export const closeIcon: string;
export const overlayContent: string;
export const overlayFooter: string;
export const button: string;
export const fixed: string;
export const overlayBg: string;
