// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const advancedSettings: string;
export const summary: string;
export const details: string;
export const open: string;
export const lockOpen: string;
