// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const fillable: string;
export const actions: string;
export const sectionHeading: string;
export const sectionNote: string;
export const attention: string;
export const userInput: string;
export const conceptDiagram: string;
export const advancedSettings: string;
export const summary: string;
export const details: string;
export const open: string;
