// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const execEditor: string;
export const currentEditor: string;
export const cmd: string;
export const task: string;
export const args: string;
export const awesomplete: string;
export const visuallyHidden: string;
export const fillable: string;
export const actions: string;
export const saveBtns: string;
export const errorResponse: string;
export const sectionHeading: string;
export const sectionNote: string;
export const attention: string;
export const userInput: string;
export const conceptDiagram: string;
export const autocompletePane: string;
export const autocompleteItem: string;
export const advancedSettings: string;
export const approvalTypeSelectors: string;
export const approvalTypeSelector: string;
export const summary: string;
export const details: string;
export const open: string;
