// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const execEditor: string;
export const comment: string;
export const caveats: string;
export const open: string;
export const currentEditor: string;
export const cmd: string;
export const task: string;
export const args: string;
