// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const sectionHeading: string;
export const sectionSubheading: string;
export const sectionNote: string;
export const attention: string;
export const userInput: string;
