// This file is automatically generated. Please do not change this file!
export const buildStatus: string;
export const jobInfo: string;
export const jobInfoBox: string;
export const key: string;
export const keyValuePair: string;
export const mappings: string;
export const names: string;
export const passedStage: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const value: string;
export const version: string;
