// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const collapse: string;
export const expanded: string;
export const error: string;
export const warning: string;
export const collapseHeader: string;
export const headerDetails: string;
export const actions: string;
export const collapseBody: string;
export const hide: string;
