// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const collapse: string;
export const expanded: string;
export const collapse_header: string;
export const collapseHeader: string;
export const header_details: string;
export const headerDetails: string;
export const actions: string;
export const collapse_body: string;
export const collapseBody: string;
export const hide: string;
