// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const hidden: string;
export const filterView: string;
export const filterByHeader: string;
export const filterByHeading: string;
