// This file is automatically generated. Please do not change this file!
export const large: string;
export const medium: string;
export const small: string;
export const tooltipContent: string;
export const tooltipContentWrapper: string;
export const tooltipWrapper: string;
