// This file is automatically generated by type-declarations-for-css-modules.ts during webpack compile. Please do not change this file!
export const large: string;
export const mappings: string;
export const medium: string;
export const names: string;
export const small: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tooltipContent: string;
export const tooltipContentWrapper: string;
export const tooltipWrapper: string;
export const version: string;
