--*************************GO-LICENSE-START*********************************
-- Copyright 2014 ThoughtWorks, Inc.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--    http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--*************************GO-LICENSE-END***********************************

CREATE TABLE AccessToken (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name           VARCHAR_IGNORECASE(255) NOT NULL,
  value          VARCHAR(255) UNIQUE NOT NULL,
  saltId         VARCHAR(8) UNIQUE NOT NULL,
  saltValue      VARCHAR(255) UNIQUE NOT NULL,
  description    VARCHAR(1024),
  isRevoked      BOOLEAN,
  revokedAt      TIMESTAMP,
  createdAt      TIMESTAMP,
  lastUsed       TIMESTAMP,
  username       VARCHAR_IGNORECASE(255) NOT NULL,
  authConfigId   VARCHAR_IGNORECASE(255) NOT NULL
);

--//@UNDO
DROP TABLE IF EXISTS AccessToken;
