--*************************GO-LICENSE-START*********************************
-- Copyright 2014 ThoughtWorks, Inc.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--    http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--*************************GO-LICENSE-END***********************************

CREATE TABLE notificationfilters (
id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
userId      BIGINT,
pipeline    VARCHAR(255),
stage       VARCHAR(255),
event           VARCHAR(50),
myCheckin       BOOLEAN
);

ALTER TABLE notificationfilters ADD CONSTRAINT fk_notificationfilters_users FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE;

--//@UNDO

DROP TABLE notificationfilters IF EXISTS CASCADE;