#!/usr/bin/env ruby

# <tailored for Go>

$LOAD_PATH << File.join(File.dirname(__FILE__), "..", "vendor", "gems", "jasmine-1.3.2", "lib")
$LOAD_PATH << File.join(File.dirname(__FILE__), "..", "vendor", "gems", "rspec-1.2.8", "lib")
$LOAD_PATH << File.join(File.dirname(__FILE__), "..", "vendor", "gems", "rack-1.0.0", "lib")
$LOAD_PATH << File.join(File.dirname(__FILE__), "..", "vendor", "gems", "jasmine-core-1.3.1", "lib")
$LOAD_PATH << File.join(File.dirname(__FILE__), "..", "vendor", "gems", "selenium-webdriver-2.35.1", "lib")
$LOAD_PATH << File.join(File.dirname(__FILE__), "..", "vendor", "gems", "childprocess-0.3.9", "lib")
$LOAD_PATH << File.join(File.dirname(__FILE__), "..", "vendor", "gems", "multi_json-1.0.0", "lib")

require 'rubygems'
require 'jasmine'

port = ENV['JASMINE_PORT'] || 8888
puts "your tests are here:"
puts "  http://localhost:#{port}/"
Jasmine.load_configuration_from_yaml
app = Jasmine::Application.app(Jasmine.config)
Jasmine::Server.new(port, app).start