// This file is automatically generated. Please do not change this file!
export const mappings: string;
export const names: string;
export const selected: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tree: string;
export const treeChild: string;
export const treeChildren: string;
export const treeChildrenLabel: string;
export const treeDatum: string;
export const version: string;
