// This file is automatically generated. Please do not change this file!
export const selected: string;
export const tree: string;
export const treeChild: string;
export const treeChildren: string;
export const treeChildrenLabel: string;
export const treeDatum: string;
