// This file is automatically generated. Please do not change this file!
export const flexBox: string;
export const jobCheckbox: string;
export const jobListContainer: string;
export const jobName: string;
export const rotate: string;
export const stageDurationContainer: string;
export const stageHeaderContainer: string;
export const stageName: string;
export const stageNameContainer: string;
export const stageNameTitle: string;
export const stageOperationButtonGroup: string;
export const stageOverviewContainer: string;
export const stageSettings: string;
export const stageTriggerAndTimingContainer: string;
