// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const pageHeader: string;
export const title: string;
export const page_title: string;
export const pageTitle: string;
