// This file is automatically generated. Please do not change this file!
export const alert: string;
export const callout: string;
export const closeCallout: string;
export const info: string;
export const success: string;
export const warning: string;
