// This file is automatically generated. Please do not change this file!
export const addArtifactWrapper: string;
export const artifactContainer: string;
export const artifactType: string;
export const builtInArtifactContainer: string;
export const builtInArtifactHeader: string;
export const idHeader: string;
export const mappings: string;
export const names: string;
export const pluginView: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
