// This file is automatically generated. Please do not change this file!
export const addArtifactWrapper: string;
export const artifactType: string;
export const builtInArtifactContainer: string;
export const builtInArtifactHeader: string;
