// This file is automatically generated. Please do not change this file!
export const cancelAfterInactivityWrapper: string;
export const mainContainer: string;
export const numberFieldWrapper: string;
