// This file is automatically generated. Please do not change this file!
export const agentCheckbox: string;
export const agentStatus: string;
export const agentsTable: string;
export const buildDetails: string;
export const building: string;
export const count: string;
export const disabled: string;
export const disabledAgent: string;
export const dropdownContent: string;
export const enabled: string;
export const headerPanel: string;
export const hostname: string;
export const leftContainer: string;
export const show: string;
export const tableCell: string;
