// This file is automatically generated. Please do not change this file!
export const addArtifactWrapper: string;
export const artifactContent: string;
export const artifactRow: string;
export const artifactsHeading: string;
export const artifactsHeadingContainer: string;
export const destination: string;
export const heading: string;
export const headingsContainer: string;
export const source: string;
export const type: string;
