// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const switchBtn: string;
export const switchLabel: string;
export const switchPaddle: string;
export const switchInput: string;
export const isSuccess: string;
export const inProgress: string;
export const switchSmall: string;
export const disabled: string;
