// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const countWrapper: string;
export const count: string;
export const green: string;
export const red: string;
