// This file is automatically generated. Please do not change this file!
export const dragIcon: string;
export const draggable: string;
export const draggableOver: string;
export const inActive: string;
export const mappings: string;
export const names: string;
export const sortButton: string;
export const sortButtonAsc: string;
export const sortButtonDesc: string;
export const sortableColumn: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const table: string;
export const version: string;
