// This file is automatically generated. Please do not change this file!
export const dragIcon: string;
export const draggable: string;
export const draggableOver: string;
export const inActive: string;
export const sortButton: string;
export const sortButtonAsc: string;
export const sortButtonDesc: string;
export const sortableColumn: string;
export const table: string;
