// This file is automatically generated. Please do not change this file!
export const dropdownContent: string;
export const instanceWrapper: string;
export const instancesList: string;
export const label: string;
export const listItem: string;
export const matchingInstanceStages: string;
export const pageHeader: string;
export const pipelineComparisonText: string;
export const pipelineInfo: string;
export const pipelineInstanceSelection: string;
export const value: string;
