// This file is automatically generated. Please do not change this file!
export const disabled: string;
export const leftPanel: string;
export const materialRevisions: string;
export const pagination: string;
export const paginationLink: string;
export const pipelineInstanceCounter: string;
export const pipelineInstanceDescription: string;
export const pipelineRun: string;
export const pipelineRunContainer: string;
export const rightPanel: string;
export const selectedInstance: string;
export const timelineModalContainer: string;
