// This file is automatically generated. Please do not change this file!
export const mappings: string;
export const names: string;
export const rotate: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const testConnectionButtonWrapper: string;
export const testConnectionFailure: string;
export const testConnectionInProgress: string;
export const testConnectionResult: string;
export const testConnectionSuccess: string;
export const version: string;
