// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const serverHealthStatuses: string;
export const serverHealthStatus: string;
export const warning: string;
export const detail: string;
export const error: string;
export const message: string;
export const timestamp: string;
export const serverHealthMessagesContainer: string;
