// This file is automatically generated. Please do not change this file!
export const configurationTypeContainer: string;
export const disabled: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const templateLink: string;
export const templateWrapper: string;
export const version: string;
