// This file is automatically generated. Please do not change this file!
export const configurationTypeContainer: string;
export const disabled: string;
export const templateLink: string;
export const templateWrapper: string;
