# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "net-sftp"
  s.version = "2.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jamis Buck", "Delano Mandelbaum"]
  s.cert_chain = ["gem-public_cert.pem"]
  s.date = "2013-05-07"
  s.description = "A pure Ruby implementation of the SFTP client protocol"
  s.email = "net-ssh@solutious.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "CHANGES.txt",
    "LICENSE.txt",
    "Manifest",
    "README.rdoc",
    "Rakefile",
    "gem-public_cert.pem",
    "lib/net/sftp.rb",
    "lib/net/sftp/constants.rb",
    "lib/net/sftp/errors.rb",
    "lib/net/sftp/operations/dir.rb",
    "lib/net/sftp/operations/download.rb",
    "lib/net/sftp/operations/file.rb",
    "lib/net/sftp/operations/file_factory.rb",
    "lib/net/sftp/operations/upload.rb",
    "lib/net/sftp/packet.rb",
    "lib/net/sftp/protocol.rb",
    "lib/net/sftp/protocol/01/attributes.rb",
    "lib/net/sftp/protocol/01/base.rb",
    "lib/net/sftp/protocol/01/name.rb",
    "lib/net/sftp/protocol/02/base.rb",
    "lib/net/sftp/protocol/03/base.rb",
    "lib/net/sftp/protocol/04/attributes.rb",
    "lib/net/sftp/protocol/04/base.rb",
    "lib/net/sftp/protocol/04/name.rb",
    "lib/net/sftp/protocol/05/base.rb",
    "lib/net/sftp/protocol/06/attributes.rb",
    "lib/net/sftp/protocol/06/base.rb",
    "lib/net/sftp/protocol/base.rb",
    "lib/net/sftp/request.rb",
    "lib/net/sftp/response.rb",
    "lib/net/sftp/session.rb",
    "lib/net/sftp/version.rb",
    "net-sftp.gemspec",
    "setup.rb",
    "test/common.rb",
    "test/protocol/01/test_attributes.rb",
    "test/protocol/01/test_base.rb",
    "test/protocol/01/test_name.rb",
    "test/protocol/02/test_base.rb",
    "test/protocol/03/test_base.rb",
    "test/protocol/04/test_attributes.rb",
    "test/protocol/04/test_base.rb",
    "test/protocol/04/test_name.rb",
    "test/protocol/05/test_base.rb",
    "test/protocol/06/test_attributes.rb",
    "test/protocol/06/test_base.rb",
    "test/protocol/test_base.rb",
    "test/test_all.rb",
    "test/test_dir.rb",
    "test/test_download.rb",
    "test/test_file.rb",
    "test/test_file_factory.rb",
    "test/test_packet.rb",
    "test/test_protocol.rb",
    "test/test_request.rb",
    "test/test_response.rb",
    "test/test_session.rb",
    "test/test_upload.rb"
  ]
  s.homepage = "https://github.com/net-ssh/net-sftp"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "net-sftp"
  s.rubygems_version = "1.8.25"
  s.signing_key = "/mnt/gem/gem-private_key.pem"
  s.summary = "A pure Ruby implementation of the SFTP client protocol"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-ssh>, [">= 2.6.5"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<net-ssh>, [">= 2.6.5"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<net-ssh>, [">= 2.6.5"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

