// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const pluginIcon: string;
export const pluginName: string;
export const pluginNotInstalled: string;
export const keyValuePair: string;
export const pluginInfoSelect: string;
export const elasticProfileModalFormBody: string;
export const tableCell: string;
export const jobSettingsLink: string;
export const disabled: string;
export const note: string;
export const spinnerWrapper: string;
