// This file is automatically generated. Please do not change this file!
export const formButton: string;
export const formHeader: string;
export const mappings: string;
export const names: string;
export const notificationWrapper: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tips: string;
export const version: string;
