// This file is automatically generated. Please do not change this file!
export const actions: string;
export const environmentVariableWrapper: string;
export const groupHeader: string;
export const infoIcon: string;
export const infoTooltipContent: string;
export const infoTooltipWrapper: string;
export const name: string;
