// This file is automatically generated. Please do not change this file!
export const actions: string;
export const environmentVariableWrapper: string;
export const groupContainer: string;
export const infoIcon: string;
export const infoTooltipContent: string;
export const infoTooltipWrapper: string;
export const mappings: string;
export const name: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
