// This file is automatically generated. Please do not change this file!
export const actions: string;
export const collapse: string;
export const collapseBody: string;
export const collapseHeader: string;
export const error: string;
export const expanded: string;
export const headerDetails: string;
export const hide: string;
export const nonCollapseHeader: string;
export const warning: string;
