// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const backupContainer: string;
export const content: string;
export const availableDiskSpace: string;
export const performBackupContainer: string;
export const performBackupSection: string;
export const backupInfo: string;
export const performBackupButtonContainer: string;
export const backupHelp: string;
export const helpHeading: string;
export const helpItem: string;
export const backupInProgress: string;
export const rotate: string;
export const backupConfigHelp: string;
