// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const backupMessage: string;
export const backupSteps: string;
export const backingUp: string;
export const backedUp: string;
export const failed: string;
export const spinner: string;
export const spin: string;
export const stepsContainer: string;
export const errorContainer: string;
