// This file is automatically generated. Please do not change this file!
export const backedUp: string;
export const backingUp: string;
export const backupMessage: string;
export const backupSteps: string;
export const errorContainer: string;
export const failed: string;
export const spin: string;
export const spinner: string;
export const stepsContainer: string;
