// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const stepsContainer: string;
export const indicator: string;
export const notRun: string;
export const running: string;
export const passed: string;
export const failed: string;
