// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const widthSmall: string;
export const infoIcon: string;
export const flexTable: string;
export const tableHeader: string;
export const hasMessage: string;
export const tableHead: string;
export const tableCell: string;
export const tableBody: string;
export const tableRow: string;
export const rulesWrapper: string;
export const warningWrapper: string;
export const warningContent: string;
