// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const keyValuePair: string;
export const key: string;
export const value: string;
export const keyValueItem: string;
export const keyValuePairInline: string;
export const keyValueInlineItem: string;
export const title: string;
