# Tanuki license keys for GoCD Server running on unix using absolute paths (uses the following license params):
# wrapper.java.mainclass=org.tanukisoftware.wrapper.WrapperJarApp
# wrapper.app.parameter.1=/usr/share/go-server/lib/go.jar

wrapper.license.type=DEV
wrapper.license.id=202605280000022
wrapper.license.licensee=ThoughtWorks
wrapper.license.group=Go
wrapper.license.dev_application=GoCD Server On Linux
wrapper.license.features=64bit
wrapper.license.key.0=4844-0af0-6c00-2370
wrapper.license.key.1=10f8-04ee-8066-569f
wrapper.license.key.2=cc27-05c6-13af-055a
wrapper.license.key.3=0ac1-865f-d37b-1cf4
wrapper.license.key.4=d7d7-27d5-ff65-9c90
