# Tanuki license keys for GoCD Agent running on unix using absolute paths (uses the following license params):
# wrapper.java.mainclass=org.tanukisoftware.wrapper.WrapperJarApp
# wrapper.app.parameter.1=/usr/share/go-agent/lib/agent-bootstrapper.jar

wrapper.license.type=DEV
wrapper.license.id=202605280000023
wrapper.license.licensee=ThoughtWorks
wrapper.license.group=Go
wrapper.license.dev_application=GoCD Agent On Linux
wrapper.license.features=64bit
wrapper.license.key.0=4844-0af0-6c00-2370
wrapper.license.key.1=ef55-f2d4-78be-27c0
wrapper.license.key.2=fd86-3abf-8977-73e6
wrapper.license.key.3=58d5-6564-ff91-f118
wrapper.license.key.4=9f5a-702b-b3d2-6e5d
