# Tanuki license keys for GoCD Server using relative paths (uses the following license params):
# wrapper.java.mainclass=org.tanukisoftware.wrapper.WrapperJarApp
# wrapper.app.parameter.1=lib/go.jar

wrapper.license.type=DEV
wrapper.license.id=202605280000025
wrapper.license.licensee=ThoughtWorks
wrapper.license.group=Go
wrapper.license.dev_application=GoCD Server
wrapper.license.features=64bit
wrapper.license.key.0=4844-0af0-6c00-2370
wrapper.license.key.1=2fac-8994-0f31-c46f
wrapper.license.key.2=327a-4d85-fe3f-67ea
wrapper.license.key.3=2c22-4fb6-eb3c-8c75
wrapper.license.key.4=3b76-dab9-4d01-4ae0
