// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const callout: string;
export const closeCallout: string;
export const success: string;
export const warning: string;
export const info: string;
export const alert: string;
