// This file is automatically generated. Please do not change this file!
export const checkboxGroup: string;
export const defaultPermissionHelpMessage: string;
export const defaultPermissionMessageBody: string;
export const defaultPermissionMessageContainer: string;
export const permissionTitle: string;
export const permissionsContainer: string;
export const specifyLocallyMessage: string;
export const stageSettingsTabContentContainer: string;
export const userAndRolesPermissions: string;
export const userCell: string;
export const usersAndRolesContainer: string;
