// This file is automatically generated. Please do not change this file!
export const allPipelinesWrapper: string;
export const configRepoLink: string;
export const header: string;
export const mappings: string;
export const names: string;
export const pipelineCheckbox: string;
export const pipelineFilterWrapper: string;
export const pipelinesContainer: string;
export const searchFieldWrapper: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
