// This file is automatically generated. Please do not change this file!
export const createEnvErrMsgContainer: string;
export const envBody: string;
export const envBodyElement: string;
export const envBodyElementHeader: string;
export const envHeader: string;
export const envName: string;
export const envVarHeading: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const tips: string;
export const version: string;
export const warningIcon: string;
export const warningTooltipContent: string;
export const warningTooltipWrapper: string;
