// This file is automatically generated. Please do not change this file!
export const envBody: string;
export const envBodyElement: string;
export const envBodyElementHeader: string;
export const envHeader: string;
export const envName: string;
export const envVarHeading: string;
