#!/bin/bash
#*************************GO-LICENSE-START********************************
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*************************GO-LICENSE-END**********************************

set -e

LOCAL_BASE=${PKG_INSTALL_ROOT}$BASEDIR/go-agent
LOCAL_WORK=${PKG_INSTALL_ROOT}/var/lib/go-agent
LOCAL_LOG=${PKG_INSTALL_ROOT}/var/log/go-agent
LOCAL_ETC=${PKG_INSTALL_ROOT}/etc

[ -d ${LOCAL_WORK}/config ] || mkdir -p ${LOCAL_WORK}/config
cp ${LOCAL_BASE}/install/config/* ${LOCAL_WORK}/config
[ -d ${LOCAL_LOG} ] || mkdir -p ${LOCAL_LOG}

# Create user and set directory permissions
grep '^go:' ${LOCAL_ETC}/passwd >/dev/null || useradd -c "Go User" -G daemon -m -d /var/go go

chown -R go:daemon ${LOCAL_WORK}
chown -R go:daemon ${LOCAL_LOG}

# Copy init script
cp -f ${LOCAL_BASE}/go-agent ${PKG_INSTALL_ROOT}/lib/svc/method

echo "Installation of Go Agent completed."

# Register the service
svccfg import ${LOCAL_BASE}/svc.xml
