// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const btnIcon: string;
export const disabled: string;
export const settings: string;
export const analytics: string;
export const edit: string;
export const clone: string;
export const remove: string;
export const lock: string;
export const close: string;
export const question: string;
export const refresh: string;
export const usage: string;
export const buttonGroup: string;
