// This file is automatically generated. Please do not change this file!
export const addMore: string;
export const allKeyVals: string;
export const defaultHeaders: string;
export const fieldGroup: string;
